#!/bin/bash
echo "Building EPUB..."
pandoc book.md -o book.epub
echo "Building HTML..."
pandoc book.md -o book.html
echo "Building PDF..."
pandoc --pdf-engine=xelatex book.md -o book.pdf
cp book.pdf 'The Puzzling Quirks of Regular Expressions.pdf'
echo "Converting to AZW3..."
ebook-convert book.epub book.azw3
echo "Converting to MOBI..."
ebook-convert book.epub book.mobi

