#!/usr/bin/env python
import re
from glob import glob

body_line = '<body epub:type="bodymatter">'
# Fragile if the order of images in book changes
solution = '<p><img src="../media/file4.svg" /></p>'
new_solution = solution + '''
<button onclick="solution()">Show/Hide Solution</button>
<div id="solution">
'''

floating_toc = open('floating-toc.html').read()

for fname in glob('HTML/text/ch*.xhtml'):
    print(f"Processing {fname}")
    with open(fname, 'r+') as fh:
        html = fh.read()
        head, sep, body = html.partition(body_line)
        if solution in html:
            sep = sep.replace('epub:type="bodymatter"',
                              'onload="solution()"')
            body = body.replace(solution, new_solution)
            body = body.replace('</section>',
                                '</div>\n</section>', 1)
        if '<figure>' in body:
            pat = re.compile('<figure>.*</figure>', re.DOTALL)
            fig = re.search(pat, html).group()
            body = body.replace(fig, "", 1)
            toc = floating_toc.replace('</div>', fig+'\n</div>', 1)
        else:
            toc = floating_toc
        html = head + sep + toc + body
    with open(fname, 'w') as fh:
        fh.write(html)
